# Generated by Django 4.1 on 2022-09-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VinBlanc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.FloatField(default=0)),
                ('origine_vin', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VinRosee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.FloatField(default=0)),
                ('origine_vin', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VinRouge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.FloatField(default=0)),
                ('origine_vin', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
