# Generated by Django 3.0.3 on 2021-08-31 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondage', '0007_auto_20210828_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 8, 31)),
        ),
    ]
