# Generated by Django 4.1 on 2022-09-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperitif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prix', models.FloatField(default=0)),
                ('ingredient', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
