# Generated by Django 4.1 on 2022-09-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aperitif', '0003_student_delete_commoninfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Tapas',
        ),
    ]
