# Generated by Django 4.1 on 2022-09-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperitif', '0004_rename_student_tapas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.FloatField(default=0)),
                ('ingredient', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Tapas',
        ),
    ]
