/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [gameorder]
      ,[game_id]
      ,[lg_id]
      ,[_iscopy]
      ,[year_id]
      ,[date_game]
      ,[seasongame]
      ,[is_playoffs]
      ,[team_id]
      ,[fran_id]
      ,[pts]
      ,[elo_i]
      ,[elo_n]
      ,[win_equiv]
      ,[opp_id]
      ,[opp_fran]
      ,[opp_pts]
      ,[opp_elo_i]
      ,[opp_elo_n]
      ,[game_location]
      ,[game_result]
      ,[forecast]
      ,[notes]
  FROM [message].[dbo].[basquet_ball]
  where game_location='H' and game_result='L'
  and notes is not null