# Generated by Django 3.2.15 on 2022-09-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nouvelle_objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_objet', models.CharField(max_length=200)),
                ('prix', models.FloatField(default=0)),
                ('ingredient', models.CharField(blank=True, max_length=200)),
                ('origine', models.CharField(blank=True, max_length=200)),
                ('commentaire', models.CharField(blank=True, max_length=200)),
                ('categorie', models.ManyToManyField(related_name='Objet', to='alcool.Categorie')),
            ],
        ),
    ]
