# Generated by Django 3.2.15 on 2022-09-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nouvelle_objet',
            new_name='Nouvelle_objet_alcool',
        ),
    ]
