# Generated by Django 3.2.15 on 2022-09-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='a_Entrees',
        ),
    ]
