# Generated by Django 3.2.15 on 2022-09-23 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20220923_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='nouveaux_plats',
            name='Identifiant_plat',
            field=models.CharField(default=datetime.datetime(2022, 9, 23, 16, 19, 43, 635912, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
