# Generated by Django 3.2.15 on 2022-09-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_nouveaux_plats_identifiant_plat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nouveaux_plats',
            old_name='origin_viande',
            new_name='origine',
        ),
    ]
