# Generated by Django 3.2.15 on 2022-09-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_origin_viande_nouveaux_plats_origine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nouveaux_Plats',
            new_name='Nouveaux_Plat',
        ),
    ]
