# Generated by Django 3.2.15 on 2022-09-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20220924_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='nouveaux_plat',
            name='ingredient',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
