# Generated by Django 3.2.15 on 2022-09-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_nouveaux_plat_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nouveaux_Plat',
            new_name='Nouvelle_objet',
        ),
        migrations.RenameField(
            model_name='nouvelle_objet',
            old_name='nom_plat',
            new_name='nom_objet',
        ),
    ]
