# Generated by Django 4.1 on 2022-09-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desserts',
            new_name='Dessert',
        ),
        migrations.RenameModel(
            old_name='Plats',
            new_name='Plat',
        ),
    ]
