# Generated by Django 4.1 on 2022-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_dessert_origin_viande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platmenuenfant',
            old_name='nom',
            new_name='nom_et_ou_prix',
        ),
        migrations.RenameField(
            model_name='prixmenuenfant',
            old_name='PrixUnique',
            new_name='commentaire',
        ),
        migrations.AddField(
            model_name='platmenuenfant',
            name='commentaire',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prixmenuenfant',
            name='nom_et_ou_prix',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
