<BoxLayoutWithActionBar>:
    orientation:"vertical"
    ActionBar:
        ActionView:
            ActionPrevious:
                title:root.title # title vient d'une propriete de BoxLayoutWithActionBar
                on_release:app.manager.pop() # plus elegant
                # on_release:root.parent.parent.pop()
                # on_release:root.parent.manager.pop()
                app_icon:"images/lab_logo.png"
                app_icon_height:"28dp"
                app_icon_width:"28dp"